### ISSUE TITLE
Can't install cargo-release

### ISSUE THREAD

**Issue by dvtomas** [sunng87/cargo-release#73]
Probably related to https://github.com/TeXitoi/structopt/issues/125

```
~$ cargo -V
cargo 1.27.0 (1e95190e5 2018-05-27)
~$ rustc -V
rustc 1.27.0 (3eda71b00 2018-06-19)
```

```
cargo install cargo-release
    Updating registry `https://github.com/rust-lang/crates.io-index`
 Downloading cargo-release v0.10.5                                              
  Installing cargo-release v0.10.5                                              
 Downloading maplit v0.1.6
 Downloading toml v0.3.2                                                        
 Downloading dirs v1.0.4                                                        
 Downloading serde v0.9.15                                                      
   Compiling proc-macro2 v0.4.24                                                
   Compiling version_check v0.1.5
   Compiling unicode-xid v0.1.0
   Compiling num-traits v0.2.6
   Compiling num-integer v0.1.39
   Compiling cfg-if v0.1.6
   Compiling unicode-segmentation v1.2.1
   Compiling unicode-width v0.1.5
   Compiling libc v0.2.43
   Compiling ucd-util v0.1.3
   Compiling lazy_static v1.2.0
   Compiling regex v0.2.11
   Compiling bitflags v1.0.4
   Compiling semver-parser v0.7.0
   Compiling serde v0.9.15
   Compiling utf8-ranges v1.0.2
   Compiling termcolor v0.3.6
   Compiling maplit v0.1.6
   Compiling quick-error v1.2.2
   Compiling textwrap v0.10.0
   Compiling memchr v2.1.1
   Compiling regex-syntax v0.5.6
   Compiling heck v0.3.0
   Compiling thread_local v0.3.6
   Compiling time v0.1.40
   Compiling dirs v1.0.4
   Compiling semver v0.6.0
   Compiling clap v2.32.0
   Compiling toml v0.3.2
   Compiling quote v0.6.10
   Compiling chrono v0.4.6
   Compiling aho-corasick v0.6.9
   Compiling syn v0.15.21
   Compiling structopt-derive v0.2.13
   Compiling structopt v0.2.13
   Compiling cargo-release v0.10.5
error: cannot find derive macro `StructOpt` in this scope
   --> src/main.rs:316:17
    |
316 | #[derive(Debug, StructOpt)]
    |                 ^^^^^^^^^

error: cannot find derive macro `StructOpt` in this scope
   --> src/main.rs:378:17
    |
378 | #[derive(Debug, StructOpt)]
    |                 ^^^^^^^^^

error[E0658]: The attribute `structopt` is currently unknown to the compiler and may have meaning added to it in the future (see issue #29642)
   --> src/main.rs:321:5
    |
321 |     #[structopt(short = "c", long = "config")]
    |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

error[E0658]: The attribute `structopt` is currently unknown to the compiler and may have meaning added to it in the future (see issue #29642)
   --> src/main.rs:325:5
    |
325 |     #[structopt(short = "m")]
    |     ^^^^^^^^^^^^^^^^^^^^^^^^^

error[E0658]: The attribute `structopt` is currently unknown to the compiler and may have meaning added to it in the future (see issue #29642)
   --> src/main.rs:329:5
    |
329 |     #[structopt(long = "sign")]
    |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^

error[E0658]: The attribute `structopt` is currently unknown to the compiler and may have meaning added to it in the future (see issue #29642)
   --> src/main.rs:333:5
    |
333 |     #[structopt(long = "dry-run")]
    |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

error[E0658]: The attribute `structopt` is currently unknown to the compiler and may have meaning added to it in the future (see issue #29642)
   --> src/main.rs:337:5
    |
337 |     #[structopt(long = "upload-doc")]
    |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

error[E0658]: The attribute `structopt` is currently unknown to the compiler and may have meaning added to it in the future (see issue #29642)
   --> src/main.rs:341:5
    |
341 |     #[structopt(long = "push-remote")]
    |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

error[E0658]: The attribute `structopt` is currently unknown to the compiler and may have meaning added to it in the future (see issue #29642)
   --> src/main.rs:345:5
    |
345 |     #[structopt(long = "skip-publish")]
    |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

error[E0658]: The attribute `structopt` is currently unknown to the compiler and may have meaning added to it in the future (see issue #29642)
   --> src/main.rs:349:5
    |
349 |     #[structopt(long = "skip-push")]
    |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

error[E0658]: The attribute `structopt` is currently unknown to the compiler and may have meaning added to it in the future (see issue #29642)
   --> src/main.rs:353:5
    |
353 |     #[structopt(long = "skip-tag")]
    |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

error[E0658]: The attribute `structopt` is currently unknown to the compiler and may have meaning added to it in the future (see issue #29642)
   --> src/main.rs:357:5
    |
357 |     #[structopt(long = "doc-branch")]
    |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

error[E0658]: The attribute `structopt` is currently unknown to the compiler and may have meaning added to it in the future (see issue #29642)
   --> src/main.rs:361:5
    |
361 |     #[structopt(long = "tag-prefix")]
    |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

error[E0658]: The attribute `structopt` is currently unknown to the compiler and may have meaning added to it in the future (see issue #29642)
   --> src/main.rs:365:5
    |
365 |     #[structopt(long = "dev-version-ext")]
    |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

error[E0658]: The attribute `structopt` is currently unknown to the compiler and may have meaning added to it in the future (see issue #29642)
   --> src/main.rs:369:5
    |
369 |     #[structopt(long = "no-dev-version")]
    |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

error[E0658]: The attribute `structopt` is currently unknown to the compiler and may have meaning added to it in the future (see issue #29642)
   --> src/main.rs:373:5
    |
373 |     #[structopt(long = "no-confirm")]
    |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

error[E0658]: The attribute `structopt` is currently unknown to the compiler and may have meaning added to it in the future (see issue #29642)
   --> src/main.rs:381:5
    |
381 |     #[structopt(name = "release")]
    |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

error[E0658]: The attribute `structopt` is currently unknown to the compiler and may have meaning added to it in the future (see issue #29642)
   --> src/main.rs:379:1
    |
379 | #[structopt(name = "cargo")]
    | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^

error: aborting due to 18 previous errors

For more information about this error, try `rustc --explain E0658`.
error: failed to compile `cargo-release v0.10.5`, intermediate artifacts can be found at `/tmp/cargo-installW8ksCU`

Caused by:
  Could not compile `cargo-release`.
```

**Comment by dvtomas** [comment]
It works with rust 1.30.1 :-)
